# [LAB 7-1] Learning rate, Evaluation

- [실습 동영상 7-1](https://youtu.be/oSJfejG2C3w): Learning rate, Evaluation
- [실습 슬라이드 7](https://docs.google.com/presentation/d/1cVwqMpERToATs1JGYps0F3MLARP8OAlw6ZIe-lpPHYs)


# Training and Test datasets

이제는 무조건 training set과 test set을 나누어서 작업!

In [3]:
import tensorflow as tf

x_data = [[1, 2, 1],
          [1, 3, 2],
          [1, 3, 4],
          [1, 5, 5],
          [1, 7, 5],
          [1, 2, 5],
          [1, 6, 6],
          [1, 7, 7]]
y_data = [[0, 0, 1],
          [0, 0, 1],
          [0, 0, 1],
          [0, 1, 0],
          [0, 1, 0],
          [0, 1, 0],
          [1, 0, 0],
          [1, 0, 0]]


# Evaluation our model using this test dataset
x_test = [[2, 1, 1],
          [3, 1, 2],
          [3, 3, 4]]
y_test = [[0, 0, 1],
          [0, 0, 1],
          [0, 0, 1]]

X = tf.placeholder("float", [None, 3]) # train할 때와 test할 때의 데이터를 다르게 입력 (X: x_data / X: x_test)
Y = tf.placeholder("float", [None, 3]) # 이게 placeholder를 사용하는 이유! 
W = tf.Variable(tf.random_normal([3, 3]))
b = tf.Variable(tf.random_normal([3]))

hypothesis = tf.nn.softmax(tf.matmul(X, W)+b)
cost = tf.reduce_mean(-tf.reduce_sum(Y * tf.log(hypothesis), axis=1))
optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.1).minimize(cost)

# Correct prediction test model
prediction = tf.argmax(hypothesis, 1)
is_correct = tf.equal(prediction, tf.argmax(Y, 1))
accuracy = tf.reduce_mean(tf.cast(is_correct, tf.float32))

# Launch graph
with tf.Session() as sess:
    # initialize tensorflow variables
    sess.run(tf.global_variables_initializer())
    for step in range(201):
        cost_val, W_val, _ = sess.run([cost, W, optimizer], feed_dict={X: x_data, Y: y_data})
        print(step, cost_val, W_val)

    # predict
    print("Prediction:", sess.run(prediction, feed_dict={X: x_test}))
    # Calculate the accuracy
    print("Accuracy: ", sess.run(accuracy, feed_dict={X: x_test, Y: y_test}))

0 5.8201036 [[ 0.84928083 -0.1306431   1.4533943 ]
 [-0.42902228  0.7168091   0.03920085]
 [ 0.06564501  1.0458636   0.2779408 ]]
1 3.7994938 [[ 0.8716869  -0.18456464  1.4849098 ]
 [-0.27217788  0.4739644   0.12520115]
 [ 0.22465716  0.8094002   0.3553921 ]]
2 2.0761998 [[ 0.88898623 -0.2209842   1.50403   ]
 [-0.12858243  0.28466326  0.17090684]
 [ 0.36998916  0.62991667  0.38954365]]
3 1.2960644 [[ 0.89216375 -0.21914892  1.4990172 ]
 [-0.03637835  0.27248484  0.09088118]
 [ 0.45737365  0.6331084   0.29896748]]
4 1.1475122 [[ 0.8753842  -0.21812189  1.5147698 ]
 [-0.03235887  0.2520576   0.10728893]
 [ 0.453686    0.6303013   0.3054622 ]]
5 1.1333203 [[ 0.85911196 -0.2143345   1.5272546 ]
 [-0.02843491  0.24735689  0.10806569]
 [ 0.45038396  0.64216256  0.29690295]]
6 1.1225166 [[ 0.8440279  -0.2118285   1.5398327 ]
 [-0.01944779  0.23626205  0.11017343]
 [ 0.4524206   0.6472516   0.2897773 ]]
7 1.1120688 [[ 0.82837695 -0.20856076  1.5522159 ]
 [-0.01444854  0.22984575  0.1115905 ]
